https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html

In [1]:
import tensorflow as tf
sess = tf.Session()

In [2]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])
sess.run(tensor)

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [3]:
tensor = tf.constant(-1.0, shape=[2, 3])
sess.run(tensor)

array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)

In [4]:
tensor = tf.fill([2, 3], 9)
sess.run(tensor)

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [5]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#linspace
tensor = tf.linspace(10.0, 12.0, 5, name="linspace")
sess.run(tensor)

array([ 10. ,  10.5,  11. ,  11.5,  12. ], dtype=float32)

In [6]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#ones
tensor = tf.ones([2, 3], tf.int32)
sess.run(tensor)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#ones_like
tensor = [[1, 2, 3], [4, 5, 6]]
sess.run(tf.ones_like(tensor))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [8]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#random_crop
tensor = [[1, 2], [3, 4], [5, 6]]
sess.run(tf.random_crop(tensor, [2,2]))

array([[1, 2],
       [3, 4]], dtype=int32)

In [9]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#random_normal
t = tf.random_normal([3,5])
sess.run(t)

array([[-0.17448927, -1.01948631,  0.999448  , -0.48549387,  0.00324767],
       [ 0.25363785,  0.28891531,  1.40596509, -0.12091599,  0.39046639],
       [ 0.9961533 ,  0.35012534,  0.08751627, -0.89189672,  0.15920395]], dtype=float32)

In [10]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#random_shuffle
t = [[1, 2],      
 [3, 4], 
 [5, 6]] 
sess.run(tf.random_shuffle(t))

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [11]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#random_uniform
t = tf.random_uniform([3,5])
sess.run(t)

array([[ 0.98765433,  0.74703765,  0.18684101,  0.27754819,  0.33030796],
       [ 0.24499655,  0.56984031,  0.23610711,  0.80156672,  0.68501782],
       [ 0.7989558 ,  0.30349481,  0.59438264,  0.39178514,  0.37943947]], dtype=float32)

In [12]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#range
sess.run(tf.range(3, 18, 3))

array([ 3,  6,  9, 12, 15], dtype=int32)

In [14]:
start = 5
start, limit = 0, start
print(start, limit)
sess.run(tf.range(5))

0 5


array([0, 1, 2, 3, 4], dtype=int32)

In [15]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#set_random_seed
tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_normal([1])
with tf.Session() as sess1:
    print(sess1.run([a,b]))
with tf.Session() as sess2:
    print(sess2.run([a,b]))

[array([ 0.17151213], dtype=float32), array([-0.42091107], dtype=float32)]
[array([ 0.17151213], dtype=float32), array([-0.42091107], dtype=float32)]


In [16]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#truncated_normal
sess.run(tf.truncated_normal([3,5]))


array([[-0.83707994, -0.12710929,  0.83837837,  0.73295081, -1.06617367],
       [-0.30760771, -1.86524987, -0.87766927, -0.2839638 , -1.19276607],
       [-0.16853231, -1.43848062, -0.13271695,  0.34223738,  1.37873077]], dtype=float32)

In [17]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#zeros
sess.run(tf.zeros([3, 4], tf.int32))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [18]:
#https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html#zeros_like
tensor = [[1, 2, 3], [4, 5, 6]]
sess.run(tf.zeros_like(tensor))

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)