In [3]:
import tensorflow as tf
import numpy as np

data = np.arange(12)

sess = tf.Session()

In [4]:
rs = tf.bitcast(data, tf.float32)
sess.run(rs)

array([[  0.00000000e+00,   0.00000000e+00],
       [  1.40129846e-45,   0.00000000e+00],
       [  2.80259693e-45,   0.00000000e+00],
       [  4.20389539e-45,   0.00000000e+00],
       [  5.60519386e-45,   0.00000000e+00],
       [  7.00649232e-45,   0.00000000e+00],
       [  8.40779079e-45,   0.00000000e+00],
       [  9.80908925e-45,   0.00000000e+00],
       [  1.12103877e-44,   0.00000000e+00],
       [  1.26116862e-44,   0.00000000e+00],
       [  1.40129846e-44,   0.00000000e+00],
       [  1.54142831e-44,   0.00000000e+00]], dtype=float32)

In [5]:
# 1-D example
tensor = [0, 1, 2, 3]
mask = [True, False, True, False]
rs = tf.boolean_mask(tensor, mask) 
sess.run(rs)

array([0, 2], dtype=int32)

In [6]:
# 2-D example
tensor = [[1, 2], [3, 4], [5, 6]]
mask = [True, False, True]
rs = tf.boolean_mask(tensor, mask) 
sess.run(rs)

array([[1, 2],
       [5, 6]], dtype=int32)

In [7]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#cast
tensor = [1.8, 2.2]
rs = tf.cast(tensor, tf.int32)
sess.run(rs)

array([1, 2], dtype=int32)

In [8]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#concat
# tensor t3 with shape [2, 3]
# tensor t4 with shape [2, 3]
# tf.shape(tf.concat(0, [t3, t4])) ==> [4, 3]
# tf.shape(tf.concat(1, [t3, t4])) ==> [2, 6]

t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
rs = tf.concat(0, [t1, t2]) 
sess.run(rs)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [9]:
rs = tf.concat(1, [t1, t2])
sess.run(rs)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)

In [10]:
# TODO
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#depth_to_space
# tf.depth_to_space(input, block_size, name=None)

In [16]:
# 't' is a tensor of shape [2]
t = [1, 2, 3]
print(sess.run(tf.expand_dims(t, 0)))
print(sess.run(tf.expand_dims(t, 1)))

[[1 2 3]]
[[1]
 [2]
 [3]]


In [12]:
rs = tf.expand_dims(t, 1)
sess.run(rs)

array([[1],
       [2],
       [3]], dtype=int32)

In [13]:
rs = tf.expand_dims(t, -1)
sess.run(rs)

array([[1],
       [2],
       [3]], dtype=int32)

In [18]:
# 't2' is a tensor of shape [2, 3, 5]
t2 = np.indices((3,5))
print(sess.run(tf.shape(t2)))
rs = tf.shape(tf.expand_dims(t2, 0))
print(sess.run(rs))
rs = tf.shape(tf.expand_dims(t2, 2))
print(sess.run(rs))
rs = tf.shape(tf.expand_dims(t2, 3))
print(sess.run(rs))
rs = tf.shape(tf.expand_dims(t2, -1))
print(sess.run(rs))

[2 3 5]
[1 2 3 5]
[2 3 1 5]
[2 3 5 1]
[2 3 5 1]


In [52]:
#https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#gather
data = np.arange(12)
rs = tf.gather(data, [2,0,2,5,9])
sess.run(rs)

array([2, 0, 2, 5, 9])

In [53]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#gather_nd
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
rs = tf.gather_nd(data, [[1,1],[2,2],[0,1]])
sess.run(rs)

array([5, 9, 2], dtype=int32)

In [55]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#one_hot
indices = [0, 2, -1, 1]
depth = 5
on_value = 1.0
off_value = 0.0
axis = -1
rs = tf.one_hot(indices, depth, on_value, off_value, axis)
sess.run(rs)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]], dtype=float32)

In [58]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#pack
rs = tf.pack([1,2,3])
print(sess.run(rs), sess.run(tf.shape(rs)))
rs = tf.unpack([1,2,3])
print(sess.run(rs))

[1 2 3] [3]
[1, 2, 3]


In [59]:
#https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#pad
t = [[1, 2, 3], [4, 5, 6]]
paddings = [[1, 2,], [3, 4]]
sess.run(tf.pad(t, paddings, "CONSTANT"))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [60]:
paddings = [[1, 1,], [2, 2]]
sess.run(tf.pad(t, paddings, "REFLECT"))

array([[6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1],
       [6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1]], dtype=int32)

In [61]:
sess.run(tf.pad(t, paddings, "SYMMETRIC"))

array([[2, 1, 1, 2, 3, 3, 2],
       [2, 1, 1, 2, 3, 3, 2],
       [5, 4, 4, 5, 6, 6, 5],
       [5, 4, 4, 5, 6, 6, 5]], dtype=int32)

In [63]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#rank
t = [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
print(sess.run(tf.shape(t)))
print(sess.run(tf.rank(t)))

[2 2 3]
3


In [64]:
t = [1, 2, 3, 4, 5, 6, 7, 8, 9]
sess.run(tf.reshape(t, [3, 3]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [65]:
t = [[[1, 1], [2, 2]],
    [[3, 3], [4, 4]]]
sess.run(tf.reshape(t, [2, 4]))

array([[1, 1, 2, 2],
       [3, 3, 4, 4]], dtype=int32)

In [66]:
t = [[[1, 1, 1],
[2, 2, 2]],
[[3, 3, 3],
[4, 4, 4]],
[[5, 5, 5],
[6, 6, 6]]]

sess.run(tf.reshape(t, [-1]))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6], dtype=int32)

In [67]:
sess.run(tf.reshape(t, [2, -1]))

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]], dtype=int32)

In [68]:
sess.run(tf.reshape(t, [-1, 9]))

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]], dtype=int32)

In [69]:
sess.run(tf.shape(tf.reshape(t, [ 2, -1, 3])))

array([2, 3, 3], dtype=int32)

In [70]:
sess.run(tf.reshape([7], []))

7

In [71]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#reverse
t = [[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]]

sess.run(tf.reverse(t, [False,False,False,False]))

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]], dtype=int32)

In [72]:
sess.run(tf.reverse(t, [False,False,False,True]))

array([[[[ 3,  2,  1,  0],
         [ 7,  6,  5,  4],
         [11, 10,  9,  8]],

        [[15, 14, 13, 12],
         [19, 18, 17, 16],
         [23, 22, 21, 20]]]], dtype=int32)

In [73]:
sess.run(tf.reverse(t, [False,True,False,True]))

array([[[[15, 14, 13, 12],
         [19, 18, 17, 16],
         [23, 22, 21, 20]],

        [[ 3,  2,  1,  0],
         [ 7,  6,  5,  4],
         [11, 10,  9,  8]]]], dtype=int32)

In [74]:
sess.run(tf.reverse(t, [False,False,True,False]))

array([[[[ 8,  9, 10, 11],
         [ 4,  5,  6,  7],
         [ 0,  1,  2,  3]],

        [[20, 21, 22, 23],
         [16, 17, 18, 19],
         [12, 13, 14, 15]]]], dtype=int32)

In [75]:
# TODO
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#reverse_sequence

In [76]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#reverse_sequence
sess.run(tf.saturate_cast(t, tf.float32))

array([[[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]]], dtype=float32)

In [77]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#shape
sess.run(tf.shape(t))

array([1, 2, 3, 4], dtype=int32)

In [78]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#shape_n
sess.run(tf.shape_n(t))

[array([2, 3, 4], dtype=int32)]

In [79]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#size
sess.run(tf.size(t))

24

In [80]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#slice
input = [[[1, 1, 1], [2, 2, 2]],
             [[3, 3, 3], [4, 4, 4]],
             [[5, 5, 5], [6, 6, 6]]]
sess.run(tf.slice(input, [1, 0, 0], [1, 1, 3]))

array([[[3, 3, 3]]], dtype=int32)

In [81]:
sess.run(tf.slice(input, [1, 0, 0], [1, 2, 3]))

array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)

In [82]:
sess.run(tf.slice(input, [0, 0, 0], [1, 2, 3]))

array([[[1, 1, 1],
        [2, 2, 2]]], dtype=int32)

In [83]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#space_to_depth
x = [[[[1], [2]],
      [[3], [4]]]]
sess.run(tf.space_to_depth(x, 2))

array([[[[1, 2, 3, 4]]]], dtype=int32)

In [84]:
x = [[[[1, 2, 3], [4, 5, 6]],
      [[7, 8, 9], [10, 11, 12]]]]
sess.run(tf.space_to_depth(x, 2))

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]], dtype=int32)

In [86]:
x = [[[1],   [2],  [3],  [4]],
     [[5],   [6],  [7],  [8]],
     [[9],  [10], [11],  [12]],
     [[13], [14], [15],  [16]]]
sess.run(tf.shape(x))

array([4, 4, 1], dtype=int32)

In [92]:
x = [[[[1],   [2],  [3],  [4]],
      [[5],   [6],  [7],  [8]],
      [[9],  [10], [11],  [12]],
      [[13], [14], [15],  [16]]]]
print(sess.run(tf.shape(x)))
x2 = sess.run(tf.space_to_depth(x, 2))
print(x2)
sess.run(tf.shape(x2))

[1 4 4 1]
[[[[ 1  2  5  6]
   [ 3  4  7  8]]

  [[ 9 10 13 14]
   [11 12 15 16]]]]


array([1, 2, 2, 4], dtype=int32)

In [93]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#split
x = np.arange(150).reshape((5, 3, 10))
print(sess.run(tf.shape(x)))
print(sess.run(tf.split(2, 2, x)))

[ 5  3 10]
[array([[[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24]],

       [[ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54]],

       [[ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84]],

       [[ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114]],

       [[120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]]]), array([[[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29]],

       [[ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59]],

       [[ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,  87,  88,  89]],

       [[ 95,  96,  97,  98,  99],
        [105, 106, 107, 108, 109],
        [115, 116, 117, 118, 119]],

       [[125, 126, 127, 

In [94]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#squeeze
t = np.arange(6).reshape((1, 2, 1, 3, 1, 1))

print(sess.run(tf.squeeze(t)))
print(sess.run(tf.shape(tf.squeeze(t))))

[[0 1 2]
 [3 4 5]]
[2 3]


In [90]:
t = np.arange(6).reshape((1, 2, 1, 3, 1, 1))
print("t", t
print "sq", sess.run(tf.squeeze(t, [2, 4]))
print "shape", sess.run(tf.shape(tf.squeeze(t, [2, -1])))

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-90-6888d51cbeed>, line 2)

In [91]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#string_to_number
# TODO

In [19]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#tile
t = [1, 2, 3, 4]
sess.run(tf.tile(t, [2]))

array([1, 2, 3, 4, 1, 2, 3, 4], dtype=int32)

```
y = torch.expand(x,10,2)
> y
 0.3837  0.3837
 0.5966  0.5966
 0.0763  0.0763
 0.1896  0.1896
 0.4958  0.4958
 0.6841  0.6841
 0.4038  0.4038
 0.4068  0.4068
 0.1502  0.1502
 0.2239  0.2239
[torch.DoubleTensor of dimension 10x2]
```

In [51]:
t = np.arange(12).reshape(-1,1)
t2 = sess.run(tf.tile(t, [1,2]))
print ("t1=",t, "t2=", t2)

t1= [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] t2= [[ 0  0]
 [ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  4]
 [ 5  5]
 [ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]
 [11 11]]


In [31]:
t = [[1, 2], [3, 4]]
sess.run(tf.tile(t, [2,2]))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]], dtype=int32)

In [96]:
# https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#unique_with_counts
# good for dic
x = [1, 1, 2, 4, 4, 4, 7, 8, 8]
y, idx, count = sess.run(tf.unique_with_counts(x))
print(y, idx, count)

[1 2 4 7 8] [0 0 1 2 2 2 3 4 4] [2 1 3 1 2]
